// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mysyneodmqiqfurhqmhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15c3luZW9kbXFpcWZ1cmhxbWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTAxMzMsImV4cCI6MjA2ODE2NjEzM30.rn_khvW7GU1vl0zsuY4Zy-02gGa7tB3vb5oUhVQXgBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});